Google-OSV test two options

diff --git a/.github/workflows/docker-build-test.yaml b/.github/workflows/docker-build-test.yaml
--- a/.github/workflows/docker-build-test.yaml
+++ b/.github/workflows/docker-build-test.yaml
@@ -44,15 +44,31 @@ jobs:
             os_version=${{ matrix.platform.os_version }}
           tags: emhass/standalone-test
           load: true
-      - name: osv-scan #Test check Docker image debian packadges for vulnerabilities 
-        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.1"
+      - name: Test #Assume Docker fail with FileNotFound secrets_emhass.yaml error
+        run: docker run --rm -it emhass/standalone-test | grep -q secrets_emhass.yaml && echo 0 || echo 1             
+      # Google OSV-Scanner  
+      - name: "Run scanner" #Test check Docker image debian packadges for vulnerabilities 
+        uses: google/osv-scanner-action/osv-scanner-action@v1.7.1
         with:
           scan-args: |-
+            --output=results.json
+            --format=json
             --recursive
             --skip-git
-            ./
             --docker emhass/standalone-test
-        permissions:
-          security-events: write    
-      - name: Test #Assume Docker fail with FileNotFound secrets_emhass.yaml error
-        run: docker run --rm -it emhass/standalone-test | grep -q secrets_emhass.yaml && echo 0 || echo 1
+            ./
+        continue-on-error: true 
+      - name: "Run osv-scanner-reporter"
+        uses: google/osv-scanner-action/osv-reporter-action@v1.7.1
+        with:
+          scan-args: |-
+            --output=${{ inputs.results-file-name }}
+            --new=results.json
+            --gh-annotations=false
+            --fail-on-vuln=${{ inputs.fail-on-vuln }}        
+      # Upload the results to GitHub's code scanning dashboard.
+      - name: "Upload to code-scanning"
+        if: "${{ !cancelled() }}"
+        uses: github/codeql-action/upload-sarif@407ffafae6a767df3e0230c3df91b6443ae8df75 # v2.22.8
+        with:
+          sarif_file: ${{ inputs.results-file-name }}
